version: '3.2'

services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    volumes:
      - $PWD:/app
    depends_on:
      - db
    env_file:
      - .env
    tty: true
    working_dir: /app/backend

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - $PWD:/app
    depends_on:
      - backend