version: '3'

services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"

  backend:
    build: 
      context: ./backend
    command: /app/entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    tty: true
