version: '3.2'

services:
  db:
    image: postgres
    networks:
      - Transcendence
    env_file:
      - .env

  backend:
    build:
      context: ./backend
    networks:
      - Transcendence
    volumes:
      - $PWD:/app
    depends_on:
      - db
    env_file:
      - .env
    tty: true
    working_dir: /app/backend

  nginx:
    build:
      context: ./nginx
    restart: always
    networks:
      - Transcendence
    ports:
      - "8000:8000"
    volumes:
      - $PWD:/app
    depends_on:
      - backend

networks:
  Transcendence:
    name: Transcendence